### ISSUE TITLE
Why require mnemonic key phrase of the address during lighthouse init?

### ISSUE THREAD

**Issue by SkyYap** [We-Bump/Lighthouse-cli#8]
I feel like it is not safe to reveal my mnemonic key phrase when I clicked `lighthouse init`

Why mnemonic keyphrase is required?

**Comment by 0xbean** [comment]
I would actually agree, shouldn't it be using the private key instead? I know hardhat from ethereum uses private keys instead of the mnemonic key.

I also have been able to find that you can still use the wallet using the `DirectSecp256k1Wallet` function instead by:
```
const wallet = await DirectSecp256k1Wallet.fromKey(Uint8Array.from(Buffer.from('private-key', 'hex')), "sei");
```

Instead of of having to use `DirectSecp256k1HdWallet`.

**Comment by sirhercules** [comment]
added private key
